- hosts: all
  become: yes
  name: Setup Finance Me Microservice and Monitoring
  tasks:
    - name: Update and upgrade the system
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Finance Me microservice container
      docker_container:
        name: finance-me-microservice
        image: suguslove10/finance-me-microservice:v1
        state: started
        restart_policy: always
        ports:
          - "8084:8081"

    - name: Download and install Node Exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        tar -xvf node_exporter-1.8.2.linux-amd64.tar.gz
        nohup ./node_exporter-1.8.2.linux-amd64/node_exporter > /dev/null 2>&1 &
      args:
        chdir: /opt

    - name: Download Prometheus configuration file
      get_url: 
        url: https://raw.githubusercontent.com/suguslove10/finance-me-microservice/master/prometheus.yml.tpl
        dest: /home/ubuntu/prometheus.yml



    - name: Generate Prometheus configuration file with Node Exporter's IP
  template:
    src: /home/ubuntu/prometheus.yml.tpl
    dest: /etc/prometheus/prometheus.yml
  vars:
    node_exporter_ip: "{{ ansible_default_ipv4.address }}"



    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
