- hosts: all
  become: yes
  vars:
    node_exporter_version: "1.8.2"
    prometheus_version: "2.53.2"
    docker_image: "suguslove10/finance-me-microservice:v1"
    prometheus_config_url: "https://raw.githubusercontent.com/suguslove10/finance-me-microservice/master/prometheus.yml"
  
  name: Setup Finance Me Microservice and Monitoring
  tasks:
    - name: Update and upgrade the system
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Finance Me microservice container
      docker_container:
        name: finance-me-microservice
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "8084:8081"

    - name: Download and install Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/opt/node_exporter-{{ node_exporter_version }}.tar.gz"

    - name: Extract Node Exporter
      unarchive:
        src: "/opt/node_exporter-{{ node_exporter_version }}.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Start Node Exporter
      command: >
        nohup /opt/node_exporter-{{ node_exporter_version }}-linux-amd64/node_exporter > /dev/null 2>&1 &
      args:
        chdir: /opt

    - name: Download and install Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/opt/prometheus-{{ prometheus_version }}.tar.gz"

    - name: Extract Prometheus
      unarchive:
        src: "/opt/prometheus-{{ prometheus_version }}.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Remove default prometheus.yml
      file:
        path: "/opt/prometheus-{{ prometheus_version }}-linux-amd64/prometheus.yml"
        state: absent

    - name: Download custom prometheus.yml
      get_url:
        url: "{{ prometheus_config_url }}"
        dest: "/opt/prometheus-{{ prometheus_version }}-linux-amd64/prometheus.yml"
        mode: '0644'

    - name: Replace placeholder in prometheus.yml with actual IP
      replace:
        path: "/opt/prometheus-{{ prometheus_version }}-linux-amd64/prometheus.yml"
        regexp: 'replace_me_with_instance_ip'
        replace: "{{ prometheus_ip }}"

    - name: Start Prometheus with the custom prometheus.yml
      command: >
        nohup /opt/prometheus-{{ prometheus_version }}-linux-amd64/prometheus --config.file=/opt/prometheus-{{ prometheus_version }}-linux-amd64/prometheus.yml > /dev/null 2>&1 &
      args:
        chdir: /opt

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
