- hosts: all
  become: yes
  name: Setup Finance Me Microservice and Monitoring
  tasks:
    - name: Update and upgrade the system
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Finance Me microservice container
      docker_container:
        name: finance-me-microservice
        image: suguslove10/finance-me-microservice:v1
        state: started
        restart_policy: always
        ports:
          - "8084:8081"

    - name: Download and install Node Exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        tar -xvf node_exporter-1.8.2.linux-amd64.tar.gz
        nohup ./node_exporter-1.8.2.linux-amd64/node_exporter > /dev/null 2>&1 &
      args:
        chdir: /opt

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
