- hosts: application_server
  become: yes
  tasks:
    - name: Update the machine
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io

    - name: Deploy Docker Container
      command: docker run -itd --name finance-me-microservice -p 8084:8081 suguslove10/finance-me-microservice:v1
    

- hosts: testing_server
  become: yes
  tasks:
    - name: Update the machine
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io

    - name: Deploy Docker Container
      command: docker run -itd --name finance-me-microservice -p 8084:8081 suguslove10/finance-me-microservice:v1

    - name: Install Node Exporter
      shell: |
        wget -q https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        tar -xvf node_exporter-1.8.2.linux-amd64.tar.gz -C /tmp
        cd /tmp/node_exporter-1.8.2.linux-amd64
        nohup ./node_exporter > /dev/null 2>&1 &

- hosts: prometheus_server
  become: yes
  tasks:
    - name: Update the machine
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Run Prometheus container
      command: docker run -d -p 9090:9090 --name prometheus -v /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

    - name: Run Grafana container
      command: docker run -d -p 3000:3000 --name grafana grafana/grafana
