- hosts: all
  become: yes
  name: Setup Finance Me Microservice and Monitoring
  tasks:
    - name: Update and upgrade the system
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Finance Me microservice container
      docker_container:
        name: finance-me-microservice
        image: suguslove10/finance-me-microservice:v1
        state: started
        restart_policy: always
        ports:
          - "8084:8081"

    - name: Download and install Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        dest: /opt/node_exporter-1.8.2.linux-amd64.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /opt/node_exporter-1.8.2.linux-amd64.tar.gz
        dest: /opt
        remote_src: yes

    - name: Start Node Exporter
      shell: |
        nohup /opt/node_exporter-1.8.2.linux-amd64/node_exporter > /dev/null 2>&1 &
      args:
        chdir: /opt

    - name: Download and install Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /opt/prometheus-2.43.0.linux-amd64.tar.gz

        - name: Extract Prometheus
      unarchive:
        src: /opt/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /opt
        remote_src: yes

    - name: Move Prometheus binaries to /usr/local/bin
      command:
        cmd: mv /opt/prometheus-2.43.0.linux-amd64/prometheus /usr/local/bin/ && mv /opt/prometheus-2.43.0.linux-amd64/promtool /usr/local/bin/

    - name: Create Prometheus configuration directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Copy Prometheus console libraries
      command:
        cmd: cp -r /opt/prometheus-2.43.0.linux-amd64/consoles /etc/prometheus/ && cp -r /opt/prometheus-2.43.0.linux-amd64/console_libraries /etc/prometheus/

    - name: Create Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']

    - name: Create Prometheus systemd service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Documentation=https://prometheus.io
          After=network.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Create Prometheus user and group
      user:
        name: prometheus
        shell: /sbin/nologin
        state: present

    - name: Create Prometheus data directory
      file:
        path: /var/lib/prometheus
        state: directory
        owner: prometheus
        group: prometheus

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "3000:3000"

