global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['PLACEHOLDER_IP:9100']

